sudo: required

services:
  - docker

install: true
script: echo "skipping test"

deploy:
  provider: script
  script: export DOCKER_TAG=$TRAVIS_TAG && ./deploy.sh
  on:
    branch: master
    tags: true