version: '3.4'

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

x-buildargs: &buildargs
  VCS_REF: ${VCS_REF}
  BUILD_DATE: ${BUILD_DATE}
  # https://hub.docker.com/_/jruby?tab=tags
  JRUBY_VERSION: ${JRUBY_VERSION}
  # https://github.com/sass/node-sass/releases/
  SASS_VERSION: ${SASS_VERSION}

services:
  jruby-yarn:
    image: awesomeinc/jruby-yarn:${TRAVIS_TAG}
    build:
      context: jre/
      args:
        <<: *proxy
        <<: *buildargs
        DOCKER_TAG: ${TRAVIS_TAG}
    environment:
      <<: *proxy
  jruby-yarn-alpine:
    image: awesomeinc/jruby-yarn:${TRAVIS_TAG}-alpine
    build:
      context: alpine/
      args:
        <<: *proxy
        <<: *buildargs
        DOCKER_TAG: ${TRAVIS_TAG}-alpine
    environment:
      <<: *proxy
  app:
    build:
      context: app/
      args:
        <<: *proxy
        <<: *buildargs
        BUILDER_BASE: awesomeinc/jruby-yarn:${JRUBY_VERSION}
        DOCKER_BASE: awesomeinc/jruby-yarn:${JRUBY_VERSION}-alpine
