version: '3.4'

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

x-buildargs: &buildargs
  VCS_REF: ${VCS_REF:-unknown}
  BUILD_DATE: ${BUILD_DATE:-unknown}
  # https://github.com/sass/node-sass/releases/
  SASS_VERSION: v4.9.4

services:
  jruby-yarn:
    image: awesomeinc/jruby-yarn:${TRAVIS_TAG:-latest}
    build:
      context: jre/
      args:
        <<: *proxy
        <<: *buildargs
        DOCKER_TAG: ${TRAVIS_TAG}
    environment:
      <<: *proxy
  jruby-yarn-alpine:
    image: awesomeinc/jruby-yarn:${TRAVIS_TAG:-latest}-alpine
    build:
      context: alpine/
      args:
        <<: *proxy
        <<: *buildargs
        DOCKER_TAG: ${TRAVIS_TAG}-alpine
    environment:
      <<: *proxy
